### ISSUE TITLE
Please update debian package

### ISSUE THREAD

**Issue by agx** [theforeman/foreman_ansible#11]
The current available version fails to work with foreman 1.10.x due to missing

https://github.com/dLobatog/foreman_ansible/commit/6220af1cd71438410ec1b750c4ff5f7e46190b6e

iirc (no near the machine atm sorry). It would be great to have a version that works unpatched. Could you update the package?

**Comment by dLobatog** [comment]
Thanks for the heads up. I've updated the gem already - https://rubygems.org/gems/foreman_ansible/versions/0.2.2

And the packaging PRs have been submitted - hopefully today we'd have a new 0.2.2 release
https://github.com/theforeman/foreman-packaging/pull/1013
https://github.com/theforeman/foreman-packaging/pull/1012
