### ISSUE TITLE
Issues with latest gem (fixed by latest PR in master)

### ISSUE THREAD

**Issue by kireevco** [theforeman/foreman_ansible#12]
FYI 
https://www.irccloud.com/pastebin/SMighr0R/

**Comment by dLobatog** [comment]
Thanks for the heads up - I published 0.2.2 with the aforementioned fix. https://rubygems.org/gems/foreman_ansible/versions/0.2.2

**Comment by dLobatog** [comment]
Packages to come in the next few hours
