### ISSUE TITLE
uninitialized constant ForemanAnsible::InsightsPlanRunner::RedhatAccess (NameError)

### ISSUE THREAD

**Issue by ohadlevy** [theforeman/foreman_ansible#140]
/home/foreman/gems/bundler/gems/foreman_ansible-b53444fe9e5e/app/services/foreman_ansible/insights_plan_runner.rb:4:in `<class:InsightsPlanRunner>': uninitialized constant ForemanAnsible::InsightsPlanRunner::RedhatAccess (NameError)

**Comment by dLobatog** [comment]
Fixed through https://github.com/theforeman/foreman_ansible/commit/f6fb798d66462701a25dabc601c6f524b60267e8
