### ISSUE TITLE
Foreman 1.16 Upgrade Validation failed: Name has already been taken (ActiveRecord::RecordInvalid)

### ISSUE THREAD

**Issue by LangJV** [theforeman/foreman_ansible#152]
We just did an upgrade of our prod environment to 1.16 (using first foreman_ansible 1.4.6 and then 1.5.2)

Upgraded instance would not startup with the following stack trace: https://pastebin.com/bXu2zf37

We did have a nonprod "equivalent" instance that upgraded a week ago with no issue, so i "believe" this is possibly related to something specific in our instance, but was hoping someone might be able to advise based on the stack trace what is going on, or why?

We first tried going from foreman_ansible 1.4.6 -> 1.5.2 and restarting the httpd service and arrived at the same stack trace error with the instance refusing to start up. Likewise running all rake tasks to try and complete the upgrade fail with the same error.
We then "removed" foreman_ansible plugin and restarted  HTTPD and we are "up" and continuing with the rake upgrade tasks without issue.

Again - my hunch is this is something specific to our config or something, as our nonprod environment upgraded no issue with this plugin, but was hoping "someone" might have some pointers based on the stack trace?

**Comment by ares** [comment]
Ansible plugin tries to create a role named "Ansible Roles Manager" but it fails since it already exists on your system. Check whether you can delete it and then try to re-add the plugin. If not, I can provide you a console command to clean that up. It seems like Foreman core issue, if the role exists, it should be skipped/renamed in case it has different permission set. But perhaps it was fixed in 1.17 only.

**Comment by LangJV** [comment]
Hey @ares this was spot on. Our installation actually somehow had two duplicate/identical roles with that name already - which may have contributed to the problem. I deleted "both" and reinstalled the plugin and the rake tasks completed with no issues. Thanks for the advice and suggestion!

**Comment by ares** [comment]
Glad that helped!
