### ISSUE TITLE
host entries duplication

### ISSUE THREAD

**Issue by angystardust** [theforeman/foreman_ansible#19]
Hi @dLobatog , I was just testing this long-awaited plugin but I discovered that every time I run `ansible host_group -m setup` new host entries are created on the foreman interface even if they already exist.
Is this the desired behavior?

Strange enough if I run a playbook on the same hostgroup, duplicate entries are created with non-fqdn hostnames.

These are the details of the environment i'm using:
- Ansible 1.9
- Foreman 1.11RC1 + foreman_ansible 0.3

**Comment by dLobatog** [comment]
@angystardust I'm not seeing that - the first time it uses the fqdn, what name do newly created hosts have?

**Comment by tbrisker** [comment]
I think this should be solved by https://github.com/theforeman/foreman_ansible/pull/55

**Comment by angystardust** [comment]
Thank you so much @tbrisker !!!
