### ISSUE TITLE
Running roles from foreman returns an OS error

### ISSUE THREAD

**Issue by ParidaPunyasloka** [theforeman/foreman_ansible#28]
I have integrated Ansible Plugin with foreman and it's working fine. Whenever i run a playbook, I could see reports getting generated in foreman. However, when I create roles under /etc/ansible/roles and enable the same for the particular host - i get the message that the roles are being run in the background but when i check /var/log/foreman/production.log, i recieve the following error :

    Traceback (most recent call last):
    File "/usr/bin/ansible-playbook", line 42, in <module>
    debug_lock = Lock()
    File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 176, in Lock
    return Lock()
    File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
    File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
    OSError: [Errno 38] Function not implemented

Thanks
Punyasloka Parida

**Comment by dLobatog** [comment]
https://groups.google.com/forum/#!searchin/foreman-users/semlock%7Csort:relevance/foreman-users/rYeOuYapIKI/Sj-Q1tuXAgAJ - closing as this isn't related to the plugin or the callback, but generally to Ansible. 

Do you get this error if you run `ansible-playbook` through the foreman user?
