### ISSUE TITLE
[No Issue] Ansible 2.1.1.0 and the Ansible plugin compability

### ISSUE THREAD

**Issue by pizzarabe** [theforeman/foreman_ansible#32]
Hi Guys,

i just wanted to give you a short command about http://projects.theforeman.org/issues/16048 (I dont wanted to create another account just to contribute to that problem...)

I had no problem with the ansible plugin, foreman 1.12.1 and ansible 2.1.1.0.

I just installed a fresh CentOS 7.2, Foreman 1.12.1 (using the repo and the install parameter "--enable-foreman-plugin-ansible")  and Ansible 2.1.1.0 from the epel repo.

I added the following lines to the /etc/ansible/ansible.conf

```
callback_plugins   = /etc/foreman/plugins/ansible_callback
bin_ansible_callbacks = True
```

downloaded the foreman_callback.py(https://github.com/theforeman/foreman_ansible/blob/master/extras/foreman_callback.py) and changed the Foreman URL and the Cert/Key Path

```
FOREMAN_URL = os.getenv('FOREMAN_URL', "https://baselfisch.bla")
# Substitute by a real SSL certificate and key if your Foreman uses HTTPS
FOREMAN_SSL_CERT = (os.getenv('FOREMAN_SSL_CERT', "/var/lib/puppet/ssl/certs/baselfisch.pem"),
                    os.getenv('FOREMAN_SSL_KEY', "/var/lib/puppet/ssl/private_keys/baselfisch.pem"))
FOREMAN_SSL_VERIFY = os.getenv('FOREMAN_SSL_VERIFY', "0")
```
(I will change the ssl verification if i have a valid cert).

If i run sth. like "ansible all -m setup" i get the facts of all my hosts within /etc/ansible/hosts at my foreman webinteface.

Just wanted to let you know...

**Comment by dLobatog** [comment]
Thanks - I'll close that bug in Redmine then :+1: :smile:

**Comment by codylane** [comment]
Apologies for the late comment, I ended up figuring out how to get FOREMAN_SSL_VERIFY to work without setting that value to 0.  I hope that this will help others.

```
# ansible --version
ansible 2.1.1.0
config file = /etc/ansible/ansible.cfg
configured module search path = Default w/o overrides
```

I ended up modifying the `foreman_callback.py` script and I'd be happy to submit a pull request on this if you would like?  

Here's the diff from the original `forman_callback.py.`

```
--- /tmp/foreman_callback.py	2016-09-24 13:59:12.394854196 -0600
+++ foreman_callback.py	2016-09-24 13:59:30.256087642 -0600
@@ -21,6 +21,9 @@
 import json
 import requests
 import time
+import socket
+
+FQDN=socket.getfqdn()
 
 try:
     from ansible.plugins.callback import CallbackBase
@@ -28,11 +31,12 @@
 except ImportError:
     parent_class = object
 
-FOREMAN_URL = os.getenv('FOREMAN_URL', "http://localhost:3000")
+FOREMAN_URL = os.getenv('FOREMAN_URL', "https://{0}".format(FQDN))
 # Substitute by a real SSL certificate and key if your Foreman uses HTTPS
-FOREMAN_SSL_CERT = (os.getenv('FOREMAN_SSL_CERT', "/etc/foreman/client_cert.pem"),
-                    os.getenv('FOREMAN_SSL_KEY', "/etc/foreman/client_key.pem"))
-FOREMAN_SSL_VERIFY = os.getenv('FOREMAN_SSL_VERIFY', "1")
+FOREMAN_SSL_CERT = (os.getenv('FOREMAN_SSL_CERT', "/etc/puppetlabs/puppet/ssl/certs/{0}.pem".format(FQDN)),
+                    os.getenv('FOREMAN_SSL_KEY', "/etc/puppetlabs/puppet/ssl/private_keys/{0}.pem".format(FQDN)),
+                    )
+FOREMAN_SSL_VERIFY = os.getenv('FOREMAN_SSL_VERIFY', "/etc/puppetlabs/puppet/ssl/certs/ca.pem")
 FOREMAN_HEADERS = {
     "Content-Type": "application/json",
     "Accept": "application/json"
```

**Comment by agx** [comment]
On Sat, Sep 24, 2016 at 01:02:21PM -0700, codylane wrote:
> Apologies for the late comment, I ended up figuring out how to get FOREMAN_SSL_VERIFY to work without setting that value to 0.  I hope that this will help others.

There's no need to modify the script, just set the environment variables

export FOREMAN_SSL_CERT="/etc/puppetlabs/puppet/ssl/certs/`hostname --fqdn`.pem"
export FOREMAN_SSL_KEY="/etc/puppetlabs/puppet/ssl/private_keys/`hostname --fqdn`.pem"
export FOREMAN_SSL_VERIFY="/etc/puppetlabs/puppet/ssl/certs/ca.pem"
ansible ...

Cheers,
 -- Guido

**Comment by tennityj** [comment]
Thanks @agx and @codylane. Both of your syntax helped me get this working on ansible 2.2.0. I also did not have to modify the script.
