### ISSUE TITLE
Plugin does not send reports to Foreman

### ISSUE THREAD

**Issue by E-M** [theforeman/foreman_ansible#34]
Hi

This plugin does not send any reports to Foreman. It sends facts but not reports. I reviewed code and I don't see where do you call send_reports function? You only call send_facts when module = setup.

**Comment by agx** [comment]
On Wed, Aug 17, 2016 at 05:15:43AM -0700, Edgars M. wrote:
> Hi
> 
> This plugin does not send any reports to Foreman. It sends facts but
> not reports. I reviewed code and I don't see where do you call
> send_reports function? You only call send_facts when module = setup.

Line 213 in extras/foreman_callback.py calls it.
 -- Guido

**Comment by agx** [comment]
On Wed, Aug 17, 2016 at 11:06:31AM -0700, Edgars M. wrote:
> Yeah, I see it now. But it still does not send reports, only facts.

Try to check if th code is actually invoked, it certainly is with the
2.0 I'm using over here (can't check a newer version easily until 2.2 is
out)

**Comment by agx** [comment]
It seems the api changed (not calling v1 and v2 APIs when v2 is not present) can you check if:

https://github.com/agx/foreman_ansible/tree/v2

helps?

**Comment by E-M** [comment]
Hi

No, that did not help. I can see in /var/log/foreman/production.log that facts are posted when I run setup module but there is nothing when I run other modules. No reports, It seems that send_reports function is not even called.

ansible 2.1.1.0
Katello 3.0.2
CentOS 7.2

```
[admin@katello.local]$ sudo ansible all -m service -a "name=ntpd state=restarted" -u admin -vvvvv
Using /etc/ansible/ansible.cfg as config file
SSH password:
SU password[defaults to SSH password]:
Loaded callback minimal of type stdout, v2.0
Loaded callback unnamed of type old, v1.0
```
This is log from setup module when facts are sent to Foreman:

> 2016-08-18 09:45:07 [app] [I] Started POST "/api/v2/hosts/facts" for 172.22.200.146 at 2016-08-18 09:45:07 +0200
> 2016-08-18 09:45:07 [app] [I] Processing by Api::V2::HostsController#facts as JSON
> 2016-08-18 09:45:07 [app] [I]   Parameters: {"name"=>"vmhost-1", "facts"=>"[FILTERED]", "apiv"=>"v2", :host=>{"name"=>"vmhost-1"}}
> 2016-08-18 09:45:12 [app] [I] Import facts for 'vmhost-1' completed. Added: 171, Updated: 11, Deleted 171 facts
> 2016-08-18 09:45:12 [app] [I] Completed 201 Created in 4608ms (Views: 7.0ms | ActiveRecord: 1000.7ms)
> 2016-08-18 09:45:21 [app] [I] Completed 200 OK in 13982ms (Views: 139.1ms | ActiveRecord: 25.6ms)

But there is nothing when I run other modules.

**Comment by agx** [comment]
On Thu, Aug 18, 2016 at 12:54:36AM -0700, Edgars M. wrote:
> Hi
> 
> No, that did not help. I can see in /var/log/foreman/production.log that facts are posted when I run setup module but there is nothing when I run other modules. No reports, It seems that send_reports function is not even called.
> 
> ansible 2.1.1.0
> Katello 3.0.2
> CentOS 7.2
> 
> ```
> [admin@katello.local]$ sudo ansible all -m service -a "name=ntpd state=restarted" -u admin -vvvvv
> Using /etc/ansible/ansible.cfg as config file
> SSH password:
> SU password[defaults to SSH password]:
> Loaded callback minimal of type stdout, v2.0
> Loaded callback unnamed of type old, v1.0
> ```
> This is log from setup module when facts are sent to Foreman:
> 
> > 2016-08-18 09:45:07 [app] [I] Started POST "/api/v2/hosts/facts" for 172.22.200.146 at 2016-08-18 09:45:07 +0200
> > 2016-08-18 09:45:07 [app] [I] Processing by Api::V2::HostsController#facts as JSON
> > 2016-08-18 09:45:07 [app] [I]   Parameters: {"name"=>"vmhost-1", "facts"=>"[FILTERED]", "apiv"=>"v2", :host=>{"name"=>"vmhost-1"}}
> > 2016-08-18 09:45:12 [app] [I] Import facts for 'vmhost-1' completed. Added: 171, Updated: 11, Deleted 171 facts
> > 2016-08-18 09:45:12 [app] [I] Completed 201 Created in 4608ms (Views: 7.0ms | ActiveRecord: 1000.7ms)
> > 2016-08-18 09:45:21 [app] [I] Completed 200 OK in 13982ms (Views: 139.1ms | ActiveRecord: 25.6ms)
> 
> But there is nothing when I run other modules.

I think reports are only sent when you run a playbook with
ansible-playbook, not ad hoc commands.

**Comment by E-M** [comment]
Hi.

Yes, you are right. It worked with ansible-playbook. Perhaps you should update documentation.
