### ISSUE TITLE
Ansible callback plugin doesnt import interface facts properly

### ISSUE THREAD

**Issue by zephyia** [theforeman/foreman_ansible#38]
I am trying to configure the foreman host for provisioning. At first the prerequistes warned me that the host didnt exsit. I then run ansible -m setup for the foreman host and the host now appears in foreman, with a bucket load of facts, however the provisiong wizard still fails the prerequiste check saying that the interfaces fact is missing. I have installed the ansible plugin on my server, configured the create_new_host_when_facts_are_uploaded and ignore_puppet_facts_for_provisioning appropriately  and tons of facts are being loaded fine just the interfaces fact doesnt seem to get created

**Comment by dLobatog** [comment]
@zephyia Interesting, can you share the facts that are being uploaded? You should see it upon running `ansible -m setup`. The plugin is using `ansible_interfaces` basically,  as you can see here https://github.com/theforeman/foreman_ansible/blob/master/app/services/foreman_ansible/fact_parser.rb#L45 

Here's an example of a JSON that's being parsed properly. https://github.com/theforeman/foreman_ansible/blob/master/test/fixtures/sample_facts.json

We might be able to help you more if you share what's on your /var/log/foreman/production.log (or whatever log you use for Foreman) when the importing happens. 

Thanks!

**Comment by dLobatog** [comment]
@zephyia Interesting, can you share the facts that are being uploaded? You should see it upon running `ansible -m setup`. The plugin is using `ansible_interfaces` basically,  as you can see here https://github.com/theforeman/foreman_ansible/blob/master/app/services/foreman_ansible/fact_parser.rb#L45 

Here's an example of a JSON that's being parsed properly. https://github.com/theforeman/foreman_ansible/blob/master/test/fixtures/sample_facts.json

We might be able to help you more if you share what's on your /var/log/foreman/production.log (or whatever log you use for Foreman) when the importing happens. 

Thanks!

**Comment by zephyia** [comment]
Here is the output of ansible foreman -m setup
`foreman | SUCCESS => {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [
            "10.192.0.200"
        ], 
        "ansible_all_ipv6_addresses": [
            "2001:44b8:41c8:c600:c0ed:e7ff:fe11:3172", 
            "fe80::c0ed:e7ff:fe11:3172"
        ], 
        "ansible_architecture": "x86_64", 
        "ansible_bios_date": "07/22/2016", 
        "ansible_bios_version": "4.6.1-xs127155", 
        "ansible_cmdline": {
            "BOOT_IMAGE": "/vmlinuz-3.10.0-327.28.3.el7.x86_64", 
            "LANG": "en_AU.UTF-8", 
            "crashkernel": "auto", 
            "quiet": true, 
            "rd.lvm.lv": "centos_ac-util1/swap", 
            "rhgb": true, 
            "ro": true, 
            "root": "/dev/mapper/centos_ac--util1-root"
        }, 
        "ansible_date_time": {
            "date": "2016-08-25", 
            "day": "25", 
            "epoch": "1472104204", 
            "hour": "05", 
            "iso8601": "2016-08-25T05:50:04Z", 
            "iso8601_basic": "20160825T055004307542", 
            "iso8601_basic_short": "20160825T055004", 
            "iso8601_micro": "2016-08-25T05:50:04.307591Z", 
            "minute": "50", 
            "month": "08", 
            "second": "04", 
            "time": "05:50:04", 
            "tz": "UTC", 
            "tz_offset": "+0000", 
            "weekday": "Thursday", 
            "weekday_number": "4", 
            "weeknumber": "34", 
            "year": "2016"
        }, 
        "ansible_default_ipv4": {
            "address": "10.192.0.200", 
            "alias": "eth0", 
            "broadcast": "10.192.0.255", 
            "gateway": "10.192.0.1", 
            "interface": "eth0", 
            "macaddress": "c2:ed:e7:11:31:72", 
            "mtu": 1500, 
            "netmask": "255.255.255.0", 
            "network": "10.192.0.0", 
            "type": "ether"
        }, 
        "ansible_default_ipv6": {
            "address": "2001:44b8:41c8:c600:c0ed:e7ff:fe11:3172", 
            "gateway": "fe80::32f7:dff:fe47:73f6", 
            "interface": "eth0", 
            "macaddress": "c2:ed:e7:11:31:72", 
            "mtu": 1500, 
            "prefix": "64", 
            "scope": "global", 
            "type": "ether"
        }, 
        "ansible_devices": {
            "sr0": {
                "holders": [], 
                "host": "IDE interface: Intel Corporation 82371SB PIIX3 IDE [Natoma/Triton II]", 
                "model": "QEMU DVD-ROM", 
                "partitions": {}, 
                "removable": "1", 
                "rotational": "1", 
                "sas_address": null, 
                "sas_device_handle": null, 
                "scheduler_mode": "cfq", 
                "sectors": "2097151", 
                "sectorsize": "512", 
                "size": "1024.00 MB", 
                "support_discard": "0", 
                "vendor": "QEMU"
            }, 
            "xvda": {
                "holders": [], 
                "host": "", 
                "model": null, 
                "partitions": {
                    "xvda1": {
                        "sectors": "1024000", 
                        "sectorsize": 512, 
                        "size": "500.00 MB", 
                        "start": "2048"
                    }, 
                    "xvda2": {
                        "sectors": "208689152", 
                        "sectorsize": 512, 
                        "size": "99.51 GB", 
                        "start": "1026048"
                    }
                }, 
                "removable": "0", 
                "rotational": "0", 
                "sas_address": null, 
                "sas_device_handle": null, 
                "scheduler_mode": "deadline", 
                "sectors": "209715200", 
                "sectorsize": "512", 
                "size": "100.00 GB", 
                "support_discard": "0", 
                "vendor": null
            }
        }, 
        "ansible_distribution": "CentOS", 
        "ansible_distribution_major_version": "7", 
        "ansible_distribution_release": "Core", 
        "ansible_distribution_version": "7.2.1511", 
        "ansible_dns": {
            "nameservers": [
                "10.192.0.3", 
                "203.0.178.191", 
                "8.8.8.8", 
                "2001:44b8:1::1", 
                "2001:44b8:2::2"
            ], 
            "search": [
                "int.packetdj.net", 
                "packetdj.net", 
                "int.packetdj.net."
            ]
        }, 
        "ansible_domain": "int.packetdj.net", 
        "ansible_env": {
            "HOME": "/home/zephyia", 
            "LANG": "en_AU.UTF-8", 
            "LC_ALL": "en_AU.UTF-8", 
            "LC_MESSAGES": "en_AU.UTF-8", 
            "LESSOPEN": "||/usr/bin/lesspipe.sh %s", 
            "LOGNAME": "zephyia", 
            "MAIL": "/var/mail/zephyia", 
            "PATH": "/usr/local/bin:/usr/bin:/opt/puppetlabs/bin", 
            "PWD": "/home/zephyia", 
            "SELINUX_LEVEL_REQUESTED": "", 
            "SELINUX_ROLE_REQUESTED": "", 
            "SELINUX_USE_CURRENT_RANGE": "", 
            "SHELL": "/bin/bash", 
            "SHLVL": "2", 
            "SSH_CLIENT": "10.192.0.200 44770 22", 
            "SSH_CONNECTION": "10.192.0.200 44770 10.192.0.200 22", 
            "SSH_TTY": "/dev/pts/3", 
            "TERM": "xterm-256color", 
            "USER": "zephyia", 
            "XDG_RUNTIME_DIR": "/run/user/1000", 
            "XDG_SESSION_ID": "4", 
            "_": "/usr/bin/python"
        }, 
        "ansible_eth0": {
            "active": true, 
            "device": "eth0", 
            "ipv4": {
                "address": "10.192.0.200", 
                "broadcast": "10.192.0.255", 
                "netmask": "255.255.255.0", 
                "network": "10.192.0.0"
            }, 
            "ipv6": [
                {
                    "address": "2001:44b8:41c8:c600:c0ed:e7ff:fe11:3172", 
                    "prefix": "64", 
                    "scope": "global"
                }, 
                {
                    "address": "fe80::c0ed:e7ff:fe11:3172", 
                    "prefix": "64", 
                    "scope": "link"
                }
            ], 
            "macaddress": "c2:ed:e7:11:31:72", 
            "module": "xen_netfront", 
            "mtu": 1500, 
            "pciid": "vif-0", 
            "promisc": false, 
            "type": "ether"
        }, 
        "ansible_fips": false, 
        "ansible_form_factor": "Other", 
        "ansible_fqdn": "foreman.int.packetdj.net", 
        "ansible_gather_subset": [
            "hardware", 
            "network", 
            "virtual"
        ], 
        "ansible_hostname": "foreman", 
        "ansible_interfaces": [
            "lo", 
            "eth0"
        ], 
        "ansible_kernel": "3.10.0-327.28.3.el7.x86_64", 
        "ansible_lo": {
            "active": true, 
            "device": "lo", 
            "ipv4": {
                "address": "127.0.0.1", 
                "broadcast": "host", 
                "netmask": "255.0.0.0", 
                "network": "127.0.0.0"
            }, 
            "ipv6": [
                {
                    "address": "::1", 
                    "prefix": "128", 
                    "scope": "host"
                }
            ], 
            "mtu": 65536, 
            "promisc": false, 
            "type": "loopback"
        }, 
        "ansible_machine": "x86_64", 
        "ansible_machine_id": "66501a8c4b9c42808e53f8010373bf2b", 
        "ansible_memfree_mb": 854, 
        "ansible_memory_mb": {
            "nocache": {
                "free": 1084, 
                "used": 746
            }, 
            "real": {
                "free": 854, 
                "total": 1830, 
                "used": 976
            }, 
            "swap": {
                "cached": 0, 
                "free": 2047, 
                "total": 2047, 
                "used": 0
            }
        }, 
        "ansible_memtotal_mb": 1830, 
        "ansible_mounts": [
            {
                "device": "/dev/mapper/centos_ac--util1-root", 
                "fstype": "xfs", 
                "mount": "/", 
                "options": "rw,seclabel,relatime,attr2,inode64,noquota", 
                "size_available": 101675126784, 
                "size_total": 104678576128, 
                "uuid": "8b5969d4-3492-4083-b2dd-fb76a325db49"
            }, 
            {
                "device": "/dev/xvda1", 
                "fstype": "xfs", 
                "mount": "/boot", 
                "options": "rw,seclabel,relatime,attr2,inode64,noquota", 
                "size_available": 216453120, 
                "size_total": 520794112, 
                "uuid": "d86218b5-6bc3-4aa9-9e97-b9a7484f607b"
            }
        ], 
        "ansible_nodename": "foreman.int.packetdj.net", 
        "ansible_os_family": "RedHat", 
        "ansible_pkg_mgr": "yum", 
        "ansible_processor": [
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz", 
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz"
        ], 
        "ansible_processor_cores": 2, 
        "ansible_processor_count": 2, 
        "ansible_processor_threads_per_core": 1, 
        "ansible_processor_vcpus": 2, 
        "ansible_product_name": "HVM domU", 
        "ansible_product_serial": "NA", 
        "ansible_product_uuid": "NA", 
        "ansible_product_version": "4.6.1-xs127155", 
        "ansible_python": {
            "executable": "/usr/bin/python", 
            "has_sslcontext": true, 
            "type": "CPython", 
            "version": {
                "major": 2, 
                "micro": 5, 
                "minor": 7, 
                "releaselevel": "final", 
                "serial": 0
            }, 
            "version_info": [
                2, 
                7, 
                5, 
                "final", 
                0
            ]
        }, 
        "ansible_python_version": "2.7.5", 
        "ansible_selinux": {
            "config_mode": "enforcing", 
            "mode": "enforcing", 
            "policyvers": 28, 
            "status": "enabled", 
            "type": "targeted"
        }, 
        "ansible_service_mgr": "systemd", 
        "ansible_ssh_host_key_ecdsa_public": "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPWMca6Y83oNAJ+nWERk34p7kIEVJQX8wpTcN914On9BYgPSX6KoHZWPE2MS7zixkwkEdKkIbq2xfw9ZmNx+qEg=", 
        "ansible_ssh_host_key_ed25519_public": "AAAAC3NzaC1lZDI1NTE5AAAAIMgVcCIksCAendPNa/EUqLN89PR6Fc1+Lye1u0Aw0ybE", 
        "ansible_ssh_host_key_rsa_public": "AAAAB3NzaC1yc2EAAAADAQABAAABAQDd20d7lonKODSN6/E+Tj8g1MQz0wPsYD9T3/APpuKBgaBWEww/2E2Y501aTO48T1Wo5pbyM/3ktNT4n0v47PW8nUGAtDmEkBRpLyMUgydP7RoQD0QeJ7nT8L1QJZk4v1QMeR7d8FvII1kA5Voz/HhPmNOpolpEmMT2kwg+QGmdYLwS9bi5L1y37xqlv7VrfGAsWI8F9msg72ypEzeH3ew+8UqVKwzV7B8ERjUzOTYGrIxCt0ik4UDArA9XtPLnWIWdiDvgk6j7S74kqErASCR1bw08sB7IWSc8dMFLZSCDtoWVUJkVVmy2rNwP2DsXOWy7PaEjKR4tn7hSf5HHAIFD", 
        "ansible_swapfree_mb": 2047, 
        "ansible_swaptotal_mb": 2047, 
        "ansible_system": "Linux", 
        "ansible_system_capabilities": [
            ""
        ], 
        "ansible_system_capabilities_enforced": "True", 
        "ansible_system_vendor": "Xen", 
        "ansible_uptime_seconds": 325, 
        "ansible_user_dir": "/home/zephyia", 
        "ansible_user_gecos": "zephyia", 
        "ansible_user_gid": 1000, 
        "ansible_user_id": "zephyia", 
        "ansible_user_shell": "/bin/bash", 
        "ansible_user_uid": 1000, 
        "ansible_userspace_architecture": "x86_64", 
        "ansible_userspace_bits": "64", 
        "ansible_virtualization_role": "guest", 
        "ansible_virtualization_type": "xen", 
        "facter_aio_agent_version": "1.6.1", 
        "facter_augeas": {
            "version": "1.4.0"
        }, 
        "facter_disks": {
            "sr0": {
                "model": "QEMU DVD-ROM", 
                "size": "1.00 GiB", 
                "size_bytes": 1073741312, 
                "vendor": "QEMU"
            }, 
            "xvda": {
                "size": "100.00 GiB", 
                "size_bytes": 107374182400
            }
        }, 
        "facter_dmi": {
            "bios": {
                "release_date": "07/22/2016", 
                "vendor": "Xen", 
                "version": "4.6.1-xs127155"
            }, 
            "chassis": {
                "type": "Other"
            }, 
            "manufacturer": "Xen", 
            "product": {
                "name": "HVM domU"
            }
        }, 
        "facter_facterversion": "3.4.1", 
        "facter_filesystems": "xfs", 
        "facter_identity": {
            "gid": 1000, 
            "group": "zephyia", 
            "privileged": false, 
            "uid": 1000, 
            "user": "zephyia"
        }, 
        "facter_is_virtual": true, 
        "facter_kernel": "Linux", 
        "facter_kernelmajversion": "3.10", 
        "facter_kernelrelease": "3.10.0-327.28.3.el7.x86_64", 
        "facter_kernelversion": "3.10.0", 
        "facter_load_averages": {
            "15m": 0.05, 
            "1m": 0.05, 
            "5m": 0.07
        }, 
        "facter_memory": {
            "swap": {
                "available": "2.00 GiB", 
                "available_bytes": 2147479552, 
                "capacity": "0%", 
                "total": "2.00 GiB", 
                "total_bytes": 2147479552, 
                "used": "0 bytes", 
                "used_bytes": 0
            }, 
            "system": {
                "available": "1.02 GiB", 
                "available_bytes": 1090105344, 
                "capacity": "43.21%", 
                "total": "1.79 GiB", 
                "total_bytes": 1919500288, 
                "used": "790.97 MiB", 
                "used_bytes": 829394944
            }
        }, 
        "facter_mountpoints": {
            "/": {
                "available": "94.69 GiB", 
                "available_bytes": 101675126784, 
                "capacity": "2.87%", 
                "device": "/dev/mapper/centos_ac--util1-root", 
                "filesystem": "xfs", 
                "options": [
                    "rw", 
                    "seclabel", 
                    "relatime", 
                    "attr2", 
                    "inode64", 
                    "noquota"
                ], 
                "size": "97.49 GiB", 
                "size_bytes": 104678576128, 
                "used": "2.80 GiB", 
                "used_bytes": 3003449344
            }, 
            "/boot": {
                "available": "206.43 MiB", 
                "available_bytes": 216453120, 
                "capacity": "58.44%", 
                "device": "/dev/xvda1", 
                "filesystem": "xfs", 
                "options": [
                    "rw", 
                    "seclabel", 
                    "relatime", 
                    "attr2", 
                    "inode64", 
                    "noquota"
                ], 
                "size": "496.67 MiB", 
                "size_bytes": 520794112, 
                "used": "290.24 MiB", 
                "used_bytes": 304340992
            }
        }, 
        "facter_networking": {
            "domain": "int.packetdj.net", 
            "fqdn": "foreman.int.packetdj.net", 
            "hostname": "foreman", 
            "interfaces": {
                "eth0": {
                    "bindings": [
                        {
                            "address": "10.192.0.200", 
                            "netmask": "255.255.255.0", 
                            "network": "10.192.0.0"
                        }
                    ], 
                    "bindings6": [
                        {
                            "address": "2001:44b8:41c8:c600:c0ed:e7ff:fe11:3172", 
                            "netmask": "ffff:ffff:ffff:ffff::", 
                            "network": "2001:44b8:41c8:c600::"
                        }, 
                        {
                            "address": "fe80::c0ed:e7ff:fe11:3172", 
                            "netmask": "ffff:ffff:ffff:ffff::", 
                            "network": "fe80::"
                        }
                    ], 
                    "ip": "10.192.0.200", 
                    "ip6": "2001:44b8:41c8:c600:c0ed:e7ff:fe11:3172", 
                    "mac": "c2:ed:e7:11:31:72", 
                    "mtu": 1500, 
                    "netmask": "255.255.255.0", 
                    "netmask6": "ffff:ffff:ffff:ffff::", 
                    "network": "10.192.0.0", 
                    "network6": "2001:44b8:41c8:c600::"
                }, 
                "lo": {
                    "bindings": [
                        {
                            "address": "127.0.0.1", 
                            "netmask": "255.0.0.0", 
                            "network": "127.0.0.0"
                        }
                    ], 
                    "bindings6": [
                        {
                            "address": "::1", 
                            "netmask": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff", 
                            "network": "::1"
                        }
                    ], 
                    "ip": "127.0.0.1", 
                    "ip6": "::1", 
                    "mtu": 65536, 
                    "netmask": "255.0.0.0", 
                    "netmask6": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff", 
                    "network": "127.0.0.0", 
                    "network6": "::1"
                }
            }, 
            "ip": "10.192.0.200", 
            "ip6": "2001:44b8:41c8:c600:c0ed:e7ff:fe11:3172", 
            "mac": "c2:ed:e7:11:31:72", 
            "mtu": 1500, 
            "netmask": "255.255.255.0", 
            "netmask6": "ffff:ffff:ffff:ffff::", 
            "network": "10.192.0.0", 
            "network6": "2001:44b8:41c8:c600::", 
            "primary": "eth0"
        }, 
        "facter_os": {
            "architecture": "x86_64", 
            "family": "RedHat", 
            "hardware": "x86_64", 
            "name": "CentOS", 
            "release": {
                "full": "7.2.1511", 
                "major": "7", 
                "minor": "2"
            }, 
            "selinux": {
                "config_mode": "enforcing", 
                "current_mode": "enforcing", 
                "enabled": true, 
                "enforced": true, 
                "policy_version": "28"
            }
        }, 
        "facter_partitions": {
            "/dev/mapper/centos_ac--util1-root": {
                "mount": "/", 
                "size": "97.51 GiB", 
                "size_bytes": 104698216448
            }, 
            "/dev/mapper/centos_ac--util1-swap": {
                "size": "2.00 GiB", 
                "size_bytes": 2147483648
            }, 
            "/dev/xvda1": {
                "mount": "/boot", 
                "size": "500.00 MiB", 
                "size_bytes": 524288000
            }, 
            "/dev/xvda2": {
                "size": "99.51 GiB", 
                "size_bytes": 106848845824
            }
        }, 
        "facter_path": "/usr/local/bin:/usr/bin:/opt/puppetlabs/bin:/usr/sbin:/sbin", 
        "facter_processors": {
            "count": 2, 
            "isa": "x86_64", 
            "models": [
                "Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz", 
                "Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz"
            ], 
            "physicalcount": 2
        }, 
        "facter_puppetversion": "4.6.1", 
        "facter_ruby": {
            "platform": "x86_64-linux", 
            "sitedir": "/opt/puppetlabs/puppet/lib/ruby/site_ruby/2.1.0", 
            "version": "2.1.9"
        }, 
        "facter_ssh": {
            "ecdsa": {
                "fingerprints": {
                    "sha1": "SSHFP 3 1 2e52f7ad2e1e360d73879c3225af2ba5da66d9bb", 
                    "sha256": "SSHFP 3 2 736c866c5fe120362bf52906beee0241a82198d019fd53e194227f5f3e016d29"
                }, 
                "key": "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPWMca6Y83oNAJ+nWERk34p7kIEVJQX8wpTcN914On9BYgPSX6KoHZWPE2MS7zixkwkEdKkIbq2xfw9ZmNx+qEg="
            }, 
            "ed25519": {
                "fingerprints": {
                    "sha1": "SSHFP 4 1 c945603760f67dd4b28eff88da213c01dec2afc3", 
                    "sha256": "SSHFP 4 2 f7143a225a1d577fafd5def8b1754ab720bff961ae1a888de6d5ed8352203b3c"
                }, 
                "key": "AAAAC3NzaC1lZDI1NTE5AAAAIMgVcCIksCAendPNa/EUqLN89PR6Fc1+Lye1u0Aw0ybE"
            }, 
            "rsa": {
                "fingerprints": {
                    "sha1": "SSHFP 1 1 2db2dd315d56256d45658a70859d9a8b7e1cfb31", 
                    "sha256": "SSHFP 1 2 3fcf068aeeade4bddc9222f5683b472ad45d99f74ffdb8ed397f7d31ede20391"
                }, 
                "key": "AAAAB3NzaC1yc2EAAAADAQABAAABAQDd20d7lonKODSN6/E+Tj8g1MQz0wPsYD9T3/APpuKBgaBWEww/2E2Y501aTO48T1Wo5pbyM/3ktNT4n0v47PW8nUGAtDmEkBRpLyMUgydP7RoQD0QeJ7nT8L1QJZk4v1QMeR7d8FvII1kA5Voz/HhPmNOpolpEmMT2kwg+QGmdYLwS9bi5L1y37xqlv7VrfGAsWI8F9msg72ypEzeH3ew+8UqVKwzV7B8ERjUzOTYGrIxCt0ik4UDArA9XtPLnWIWdiDvgk6j7S74kqErASCR1bw08sB7IWSc8dMFLZSCDtoWVUJkVVmy2rNwP2DsXOWy7PaEjKR4tn7hSf5HHAIFD"
            }
        }, 
        "facter_system_uptime": {
            "days": 0, 
            "hours": 0, 
            "seconds": 326, 
            "uptime": "0:05 hours"
        }, 
        "facter_timezone": "UTC", 
        "facter_virtual": "xenu", 
        "module_setup": true
    }, 
    "changed": false
}`


The lines from the log are as follows:

`==> /var/log/foreman/production.log <==
2016-08-25 05:50:04 [app] [I] Started POST "/api/v2/hosts/facts" for 10.192.0.200 at 2016-08-25 05:50:04 +0000
2016-08-25 05:50:04 [app] [I] Processing by Api::V2::HostsController#facts as JSON
2016-08-25 05:50:04 [app] [I]   Parameters: {"name"=>"foreman", "facts"=>"[FILTERED]", "apiv"=>"v2", :host=>{"name"=>"foreman"}}

==> /var/log/httpd/foreman-ssl_access_ssl.log <==
10.192.0.200 - - [25/Aug/2016:05:50:04 +0000] "POST /api/v2/hosts/facts HTTP/1.1" 201 844 "-" "python-requests/2.6.0 CPython/2.7.5 Linux/3.10.0-327.28.3.el7.x86_64"

==> /var/log/foreman/production.log <==
2016-08-25 05:50:06 [app] [I] Import facts for 'foreman' completed. Added: 363, Updated: 0, Deleted 0 facts
2016-08-25 05:50:07 [app] [I] Completed 201 Created in 2882ms (Views: 2.6ms | ActiveRecord: 222.1ms)`

You can see that anisble_interface is in the json output and it also shows up in the facts of the web interface as:

foreman.int.packetdj.net	| ansible_interfaces	| ["lo", "eth0"]	| 3 minutes ago

I wonder if the order of the elements in the array is an issue?

**Comment by dLobatog** [comment]
The parser has changed and it's using the one from Foreman core - closing as it probably works now
