### ISSUE TITLE
Ansible playbook run overwrites production.log

### ISSUE THREAD

**Issue by karras** [theforeman/foreman_ansible#42]
When pressing the "Ansible roles" button to execute the playbook against a host it overwrites the production.log.

Instead the output should be appended to the log file.

**Comment by tongpu** [comment]
Added to Foreman Redmine: http://projects.theforeman.org/issues/16413

**Comment by tongpu** [comment]
Fix implemented in #44

**Comment by dLobatog** [comment]
The way roles will run in the next release will change drastically (it will run via foreman-tasks and will be able to run via the proxy) - so I'm not sure this error is relevant now. In any case, I'll leave it open to make sure it doesn't happen when   https://github.com/theforeman/foreman_ansible/pull/40 is merged

**Comment by dLobatog** [comment]
Closing as https://github.com/theforeman/foreman_ansible/pull/40 stores logs in tasks
