### ISSUE TITLE
Foreman plugin does not import facts correctly

### ISSUE THREAD

**Issue by haasn** [theforeman/foreman_ansible#58]
I'm trying to use foreman as a way to manage and inventorize ansible hosts. I'm trying to use the feature where ansible facts will automatically be collected by puppet.

Looking at a host I can see that it successfully captures ansible facts, i.e. there's a big tree `ansible_facts` which contains all the info you'd ever want about the host. However, this data does not get parsed/recognized/whatever in terms of the foreman facts, i.e. stuff like “operating systems” or “NICs” still shows blank values even though the values are all available via `ansible_facts::...`.

Not sure what I'm doing wrong or how to find it out. I followed the manual installation guide at https://theforeman.org/manuals/1.13/index.html#3.3InstallFromPackages and https://theforeman.org/plugins/foreman_ansible/1.x/index.html#2.Installation

**Comment by agx** [comment]
On Fri, Nov 25, 2016 at 04:58:44AM -0800, Niklas Haas wrote:
> I'm trying to use foreman as a way to manage and inventorize ansible hosts. I'm trying to use the feature where ansible facts will automatically be collected by puppet.
> 
> Looking at a host I can see that it successfully captures ansible facts, i.e. there's a big tree `ansible_facts` which contains all the info you'd ever want about the host. However, this data does not get parsed/recognized/whatever in terms of the foreman facts, i.e. stuff like “operating systems” or “NICs” still shows blank values even though the values are all available via `ansible_facts::...`.
> 
> Not sure what I'm doing wrong.

I saw s.th. similar when not having the foreman_ansible plugin installed
in foreman. Did you check under plugins that it's detected correctly?

**Comment by haasn** [comment]
I installed the plugin via `apt install ruby-foreman-ansible`.

```
% ll -a /etc/foreman/plugins                                                                                                                                                                                        
total 14K
drwxr-xr-x 2 root root   3 Nov 25 13:42 .
drwxr-xr-x 3 root root  10 Nov 25 13:42 ..
-rw-r--r-- 1 root root 680 Sep 20 09:54 foreman-tasks.yaml
```

Not sure where else to show. I don't see a “plugins” tab in the foreman settings or anything of that nature.

**Comment by dLobatog** [comment]
The plugins tab is on 'Administer > About', like this:

![screenshot from 2016-11-25 14-34-17](https://cloud.githubusercontent.com/assets/598891/20626816/60932692-b31c-11e6-9d5e-295f8819743d.png)

@haasn Would you mind to give us the logs you see when you run Ansible and the facts are imported? You should see something like `2016-11-25T14:35:29 617a87bf [app] [D] Importer ForemanAnsible::StructuredFactImporter does not implement authorized_smart_proxy_features.`, if the plugin is installed properly - probably it's `ForemanAnsible::FactImporter` in your case.

Notice you should restart apache after installing any plugin 😄  (@mmoll does apt restart the service after installing plugins by any chance)

**Comment by agx** [comment]
On Fri, Nov 25, 2016 at 05:06:36AM -0800, Niklas Haas wrote:
> I installed the plugin via `apt install ruby-foreman-ansible`.
> 
> ```
> % ll -a /etc/foreman/plugins                                                                                                                                                                                        
> total 14K
> drwxr-xr-x 2 root root   3 Nov 25 13:42 .
> drwxr-xr-x 3 root root  10 Nov 25 13:42 ..
> -rw-r--r-- 1 root root 680 Sep 20 09:54 foreman-tasks.yaml
> ```
> 
> Not sure where else to show. I don't see a “plugins” tab in the foreman settings or anything of that nature.

Administer -> About -> Plugins

**Comment by haasn** [comment]
Ah, `systemctl restart foreman` did the trick :)

It still doesn't seem to get recognized for all of the hosts though, only some. I'll try deleting the hosts and re-importing them from scratch.

**Comment by mmoll** [comment]
DEBs don't restart anything, known issue...

**Comment by dLobatog** [comment]
@haasn If you don't mind I'll close this then - glad you got it working now 😄 . It's possible that it's not detecting the fqdn properly for some of your hosts, this will be fixed in next weeks' release https://github.com/theforeman/foreman_ansible/commit/bd1a3baa07b19f2d049de7407b7645c9a4c50bb7 

In any case I'd be happy to hear about any other issues you may have 👍
