### ISSUE TITLE
How to use host vars in foreman ?

### ISSUE THREAD

**Issue by petarkozic** [theforeman/foreman_ansible#59]
I was installed and configure foreman. Add new host is working, but when I try to play some roles I give error because foreman try to connect on host over ssh_port 22, but I want something other.

When I use ansimble from command line, I set host vars and I have ansible_ssh_port= ; ansible_ssh_user=; etc...

How can I resolve this in foreman ?
Thanks !

**Comment by tbrisker** [comment]
https://github.com/theforeman/foreman_ansible/pull/60 should provide a first step in resolving this issue.

**Comment by dLobatog** [comment]
@petarkozic Those argument can be sent via Host parameters already, have you tried that? You'd make parameters on the last tab of the Host form, and they'd have keys like "ansible_ssh_port" and values like "22". As @tbrisker said before we're working to make this more obvious and usable. Thanks !

**Comment by petarkozic** [comment]
@dLobatog Yes. I try to send as Host parameter but don't work. Only work if I set host_port in ansible.cfg, but that's not sutable for me and my environment. Thank you on response, I will wait for some update.

**Comment by dLobatog** [comment]
@petarkozic Yeah - I wrote that too hastily, those params are not send at a 'top-level' , which is what #60 partly fixes. Thanks for reporting this, we'll make a release soon to include the fix

**Comment by dLobatog** [comment]
Closing as the PR has been merged - expect a new minor release tomorrow with this.
