### ISSUE TITLE
Multiple folders in /etc/ansible/ansible.cfg roles_path

### ISSUE THREAD

**Issue by ondrejlevy** [theforeman/foreman_ansible#84]
Fix #18311 does not support multiple folder in role_path. It will be very usefull especialy in situation when roles is pulled from multiple source control repository and is not possible to have all roles in one folder.

Example:

roles_path = /opt/mysite/roles:/opt/othersite/roles

This syntax is in ansible.cfg supported in version 1.4 and newer (http://docs.ansible.com/ansible/intro_configuration.html#roles-path)

**Comment by dLobatog** [comment]
Thanks! Cloned to Redmine http://projects.theforeman.org/issues/20489 - I'll try to make a fix for the version after the next minor one.

**Comment by dLobatog** [comment]
Need to make a release but this is done

**Comment by dforsberg** [comment]
Hi,

This still dosent work for me. I am running this release: tfm-rubygem-foreman_ansible-1.4.5-1.fm1_15.el7.noarch
