### ISSUE TITLE
Facts import not happening

### ISSUE THREAD

**Issue by vinneh** [theforeman/foreman_ansible#86]
I am using ansible and foreman on centos7.
Installed everything through the repos.
I can see the ansible plugin installed under administer-> about.
When I run a playbook I do see the report in foreman, I get a notification that something changed, I see the step where it gathered facts and I see all the ansible facts.
But all the fields where the facts need to be in the GUI are empty.
One thing I noticed in my production log is that it's only doing the "Imported facts for '<host>'"  step for the one puppet node, not for the ansible nodes. I only see the reports getting imported for them. So I am guessing thats where it goes wrong. But how do I make it import the facts for the ansible nodes? Like I said the plugin seems to be loaded and active. 
Thanks in advance for any help.

**Comment by terra-nova** [comment]
I am having the same issue.

Running on CentOS 7.3 with Ansible 2.3 from EPEL.


From lookin over the Foreman callback that comes with Ansible (/usr/lib/python2.7/site-packages/ansible/plugins/callback/foreman.py), it seems that the `send_facts()` function is only ever called if there is a sub-key "module-name" under the "invocation" key and if that keys' value is "setup".

```
...
        try:
            module = res['invocation']['module_name']
        except KeyError:
            module = None

        if module == 'setup':
            host = result._host.get_name()
            self.send_facts(host, res)
...
```

However, on my system, the "invocation" structure does not have a key named "module_name" (the output below is what I get from runnign `ansible localhost -m setup`):

```
   u'invocation':{
      u'module_args':{
         u'filter':u'*',
         u'gather_subset':[
            u'all'
         ],
         u'fact_path':u'/etc/ansible/facts.d',
         u'gather_timeout':10
      }
   },
```

The closest thing I could find is a sub-key "module_setup" under the "ansible_facts" key:

```
...
   u'ansible_facts':{
      ...
      u'module_setup':True,
      ...
   },
...
```

So I went ahead and modifed the callback module as follows:

```
    def v2_runner_on_ok(self, result):
        res = result._result
        try:
            has_facts = res['ansible_facts']['module_setup']
        except KeyError:
            has_facts = False

        try:
            module = res['invocation']['module_name']
        except KeyError:
            module = None

        if module == 'setup' or has_facts == True:
            host = result._host.get_name()
            self.send_facts(host, res)
        else:
            self.append_result(result)
```

With this change I was able to send facts collected with Ansible to Foreman. I would be very interested in a definitive ("official") solution, though.

Kind Regards

**Comment by vinneh** [comment]
Wow. You rock. I made your adjustment and I am getting the facts now. Thanks so much!

**Comment by igelkotten** [comment]
Great, works here also!

**Comment by mroeh** [comment]
Hi,
I was happy to found this thread because I have exact the same problem in the same environment. I did the mentioned changes but for me it still do not work :-(
So I would kindly ask for more information: Are there any log files I can check ? Must I change something more in the foreman configuration ? Can the passenger module be the problem ?
I appreciate every hint :-)
Best regards

**Comment by dLobatog** [comment]
@terra-nova Can you give a bit more information about your setup? Like, OS version, python & ansible version, etc.. I have never seen module_name not show up, hence why the callback relied on it. Your patch is probably a good solution, feel free to submit it to https://github.com/ansible/ansible/blob/5553b208281d723ead1e61be5c37227ec2b2736e/lib/ansible/plugins/callback/foreman.py and mention me - I might submit it myself in a couple of days if you do not 😄  Thanks !

**Comment by ToroNZ** [comment]
Had this exact issue, though the @terra-nova mod did not fix it completely.

If I click on 'facts' I get this error:
![image](https://cloud.githubusercontent.com/assets/8522935/26814193/ab894be2-4ad7-11e7-9c2d-ebc8e6860a2d.png)

**Comment by ankush-grover-3pg** [comment]
I have the same problem and the above code changes in foreman.py did not solve the problem. Any update when this will be fixed officially??

**Comment by igelkotten** [comment]
@dLobatog 

I don't know if you got a hold on terranova but. Centos 7 fully updated.

ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

The problem was fixed with his fix.

**Comment by igelkotten** [comment]
@ankush-grover-3pg

What versions are you running? Did you follow the guide? Are you sure you are messing with the right file(if you also put in a print statement "this file" or something that you can see?

**Comment by mroeh** [comment]
Hi,

it is frustrating: I run a complete new setup (OS and foreman) and the importing does not run anyway :-(
I have the same version as igelkotten:
ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

I try the original callback script from the ansible rpm and the modified one from terra-nova, none of them works.  ansible -m setup localhost shows all the facter information:
localhost | SUCCESS => {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [
            "192.168.178.64"
        ], 
        "ansible_all_ipv6_addresses": [
            "fe80::515e:9f7a:4853:f3e7"
        ], 
        "ansible_apparmor": {
            "status": "disabled"
        }, 
        "ansible_architecture": "x86_64", 
        "ansible_bios_date": "07/21/2008", 
        "ansible_bios_version": "1.00", 
......

I checked with a print statement that the right script is used, but no error messages, no import of facts.

Because of using passenger the FOREMAN_URL is https://<servername> , ssl verify is off:
FOREMAN_SSL_VERIFY=false

Has anybody a hint ?

**Comment by mroeh** [comment]
I'm a step forward:
In ansible.cfg the foreman callback module must be insert in the whitelist eg. 
callback_whitelist = foreman

Now the callback module will run into the v2_runner_on_ok section (checked with a print statement), but still nothing will be imported and I get this message:
 [WARNING]: Failure using method (v2_runner_on_ok) in callback plugin (</usr/lib/python2.7/site-packages/ansible/plugins/callback/foreman.CallbackModule object at 0x2b3c910>): [Errno 2]
No such file or directory

Has anybody an idea what to do now ?

**Comment by mroeh** [comment]
It works now :-)

Though I set FOREMAN_SSL_VERFIY to false the callback uses ssl. So I set all variables:
export FOREMAN_URL="https://<foreman-server>"
export FOREMAN_SSL_CERT="/etc/puppetlabs/puppet/ssl/certs/<foreman-server>.pem"
export FOREMAN_SSL_KEY="/etc/puppetlabs/puppet/ssl/private_keys/<foreman-server>.pem"
export FOREMAN_SSL_VERIFY="True"

Now after running an ansible -m setup <server> the server was created in foreman and the facts were imported.

So a quick solution summary:
- add the callback_whitelist entry in ansible.cfg
- modify the foreman.py script as mentioned by terra-nova
- set all FOREMAN env variables for using ssl

**Comment by dLobatog** [comment]
@mroeh Interesting - I thought @terra-nova solution would be only for Ansible 2.2 but on 2.3 it'd be fixed.

Points 1 and 3 from your quick solution summary are available on https://theforeman.org/plugins/foreman_ansible/1.x/index.html , however, if you found other problems, I'd appreciated any updates on https://github.com/theforeman/theforeman.org/blob/gh-pages/plugins/foreman_ansible/1.x/index.md 😄 

Thanks for your effort troubleshooting !

**Comment by ankush-grover-3pg** [comment]
I had the old code Commented Out with "#" in the foreman.py file and the new code also. After removing the old code the facts are getting imported.  Thanks everyone..

**Comment by agx** [comment]
@mroeh Note that FOREMAN_SSL_VERFIY only toggle whether the client validates the cert presented by the server. You still need to setup client certificates for authentication if using https.

**Comment by agx** [comment]
@mroeh  I added a better error message for the case of missing certs:

https://github.com/ansible/ansible/pull/25796

**Comment by agx** [comment]
Just for the record: I just verified that importing facts and reports works as expected in current ansible 'devel' branch with a fix for terra novas issue in @terra-nova: 
https://github.com/ansible/ansible/commit/7c308b3f8cd0b7f0563890773c77f5bf0ace8cd2 
so should we close this one?

**Comment by Bluesboy** [comment]
@agx wait please, I have the same issue. My setup is
```
#uname -a
Linux theforeman.example.com 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
#cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)`
#ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```
Foreman uses FreeIPA integration and to invoke ansible module I'm using
```
ansible -m setup ipa00.example.com -u myname
```
And then nothing happens )-:
I've modified `foreman.py` as @terra-nova suggested, but everything stays the same.
I have no idea where to look for troubleshoot this issue.
Tanks in advance.

**Comment by agx** [comment]
@Bluesboy I'm using thist for testing. I assume you're missing 
ANSIBLE_LOAD_CALLBACK_PLUGINS=treue:

```
#!/bin/bash

set -e

cat <<EOF > ansible.cfg
[defaults]
callback_whitelist = foreman
EOF

. hacking/env-setup

export FOREMAN_URL=https://10.0.1.15
export FOREMAN_SSL_CERT=../cert.pem
export FOREMAN_SSL_KEY=../cert.key
export FOREMAN_SSL_VERIFY=0
export ANSIBLE_LOAD_CALLBACK_PLUGINS=true

if [ -z "$TEST_REPORT" ]; then
    ansible -i localhost, -msetup -clocal localhost
else
    ansible-playbook -i localhost, ../test.yml -clocal -l localhost
fi
```

If nothing happens this is not the issue @terra-nova reported so I'm still inclined to close that one.

**Comment by Bluesboy** [comment]
@agx you were completely right, after I exported `ANSIBLE_LOAD_CALLBACK_PLUGINS=true` all went well. I've also manually downloaded `mail.py` and `foreman.py` from Ansible devel branch.
Obviously I've should get better understanding of how Ansible works, before posting my comment. A was thinking that adding `callback_whitelist = foreman` was enough, but it wasn't. You know how people can be inattentive, when something doesn't work despite you doing everything accordingly to manual.
Thank you very much.

**Comment by Bluesboy** [comment]
I just uncommented option `bin_ansible_callbacks = True` in `/etc/ansible/ansible.cfg` instead of exporting `ANSIBLE_LOAD_CALLBACK_PLUGINS` and it works fine now! It mentioned in foreman-ansible plugin manual, but only for versions older than 2.2. Since I'm using ansible-2.3 this part of manual is wrong, could you correct this for future generations?
Regards.

**Comment by agx** [comment]
On Fri, Jun 16, 2017 at 11:17:36AM -0700, Shamil Sattarov wrote:
> I just uncommented option `bin_ansible_callbacks = True` in `/etc/ansible/ansible.cfg` instead of exporting `ANSIBLE_LOAD_CALLBACK_PLUGINS` and it works fine now! It mentioned in foreman-ansible plugin manual, but only for versions older than 2.2. Since I'm using ansible-2.3 this part of manual is wrong, could you correct this for future generations?
> Regards.

Both are equivalent AFAICT so either one is sufficient:

     http://docs.ansible.com/ansible/intro_configuration.html#bin-ansible-callbacks

**Comment by dLobatog** [comment]
@bluesboy You're right, the docs mention to activate the callback 2.2+ but it doesn't mention "bin_ansible_callbacks = True" - I took that for granted. https://github.com/theforeman/theforeman.org/pull/898

**Comment by agx** [comment]
Closing this one now that @dLobatog doc update to foreman is also merged.
