### ISSUE TITLE
Unable to set ansible_ssh_private_key_file and ansible_ssh_common_args using Foreman host/group parameters

### ISSUE THREAD

**Issue by terra-nova** [theforeman/foreman_ansible#87]
White it is possible to override the ansible_user, ansible_pass, ansible_port, and ansible_host parameters using Foreman host/group parameters, no such support exists for other equally important Ansible parameters, like ansible_ssh_private_key_file (for those users who would prefer SSH pub key authentication over password authentication) or ansible_ssh_common_args (for utilizing the OpenSSH ProxyCommand parameter for example).

Special treatment for ansible_host, ansible_port, ansible_user, and ansible_pass has been implemented in MR #60. Unless there is a specific reason for only supporting password authentication, I propose to add ansible_ssh_private_key_file and ansible_ssh_common_args to this list of variables.

**Comment by dLobatog** [comment]
ACK, this sounds like a sane RFE.  I've opened http://projects.theforeman.org/issues/19758 to keep track of it if you don't mind to follow the discussion there. Thanks @terra-nova !
